// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFdDMj5hhbhAqus8126RO1nM-4rhYN2Fo',
    appId: '1:552111998838:web:22c4243be9c467ed479c57',
    messagingSenderId: '552111998838',
    projectId: 'inker-5ff7d',
    authDomain: 'inker-5ff7d.firebaseapp.com',
    storageBucket: 'inker-5ff7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbWONRCMDfnWi94rJ8CDH6XlYmwMdR-eQ',
    appId: '1:552111998838:android:f7e13464c54f846f479c57',
    messagingSenderId: '552111998838',
    projectId: 'inker-5ff7d',
    storageBucket: 'inker-5ff7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrulb3J-fEMNvzjzn1Pecq5zqhJT5WN8I',
    appId: '1:552111998838:ios:a55e8513bd40473f479c57',
    messagingSenderId: '552111998838',
    projectId: 'inker-5ff7d',
    storageBucket: 'inker-5ff7d.firebasestorage.app',
    androidClientId: '552111998838-1if35cntcivie48spfcdcagfc0vcridq.apps.googleusercontent.com',
    iosClientId: '552111998838-urqsaan8q1ba7gn62loaa9kh1heohcf2.apps.googleusercontent.com',
    iosBundleId: 'com.inkerapp.inker',
  );
}
